### ISSUE TITLE
carthage 0.14.0 complaining about missing shared framework schemes

### ISSUE THREAD

**Issue by amccarri** [jspahrsummers/libextobjc#108]
Trying to add a carthage dependency on libextobjc and getting the following when running carthage update or carthage bootstrap:

```
*** Checking out libextobjc at "0.4.1"
*** xcodebuild output can be found in /var/folders/zx/_rxl1j717bb2bwk2g4wf0dcw0000gp/T/carthage-xcodebuild.hMhDtz.log
*** Skipped building libextobjc due to the error:
Dependency "libextobjc" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/jspahrsummers/libextobjc/issues/new
```

In the carthage checkout folder, the schemes do exist in the xcschemes folder.  I suspect this is a bug in carthage but filing here as well in case there is a workaround such as maybe simplifying the scheme names.

**Comment by jspahrsummers** [comment]
The error message is correct, but it's By Design™. libextobjc is not meant to be used as a monolithic framework. Please see [the instructions in the README](https://github.com/jspahrsummers/libextobjc/tree/371b8da18f163a8f7f8925ad6d592d7b3b82ad05#adding-to-your-project).
