### ISSUE TITLE
Feature to avoid checks of object responds to selector

### ISSUE THREAD

**Issue by k06a** [jspahrsummers/libextobjc#111]
Wanna contribute new feature to libextobjc:
https://github.com/ML-Works/orNil

And maybe we just need to find more suitable name for libextobjc usage?

What do you think?

**Comment by jspahrsummers** [comment]
This library isn't under active feature development anymore, since Swift is the more or less the way forward. I'll accept bug fixes, but I can't accept the responsibility of curating new features. Feel free to fork the library, though!

Sorry about that. :confused:
