### ISSUE TITLE
Collision aversion

### ISSUE THREAD

**Issue by grgcombs** [jspahrsummers/libextobjc#112]
Seems like collision issues pop up a lot given the extreme utility of this library. You've mentioned before that git subtree merges are the go to solution, but this seems like a trail of tears for anyone that wants to undertake it. More often than not I think a lot of folks just take the risk and likely suffer later.

Thinking about this -- where are all the usual pinch points on the symbol collisions? Obviously things like "ambiguous" @strongify and @weakify come up a lot, but so does @onExit, and I'm betting a number of meta-macros do too. 

What about a pre-build script that injects the consumer's desired prefix in all the necessary places. Thinking it'd stay out of the way and optional (or use directly in apps) unless you needed it (such as when distributing a public framework).

Whatever the case, if there's a universally approved/acceptable way to get the prefixes in *most* of the right spots, it'd be great to have some way to automate that...

**Comment by k06a** [comment]
You can just:
```
#define strongify xxx_strongify
#define weakify xxx_weakify
#define onExit xxx_onExit
#import <libextobjc/extobjc.h>
#undef strongify
#undef weakify
#undef onExit
```

**Comment by grgcombs** [comment]
Ahh, of course!  That's perfect!

**Comment by k06a** [comment]
@grgcombs do not forget to import Foundation before libextobjc, if you're using version < 0.5.0 :)
