### ISSUE TITLE
questions regarding ext_strongify_

### ISSUE THREAD

**Issue by haifengkao** [jspahrsummers/libextobjc#113]
```
#define ext_weakify_(INDEX, CONTEXT, VAR) \
    CONTEXT __typeof__(VAR) metamacro_concat(VAR, _weak_) = (VAR);

#define ext_strongify_(INDEX, VAR) \
    __strong __typeof__(VAR) VAR = metamacro_concat(VAR, _weak_);
```
the above macro creates something like: 
__weak __typeof__(self) self_weak_ = self;
__strong __typeof__(self) self = self_weak_;
 　　　　　　　                                ^^^
               　　　　　　　                    will `(self)` create the retain cycle inside the block (because it is not shadowed)?

**Comment by kastiglione** [comment]
> will `(self)` create the retain cycle inside the block (because it is not shadowed)?

It will not create a retain cycle, because `__typeof(self)` is a compile time expression, not a runtime one.

**Comment by haifengkao** [comment]
got it. thanks
