### ISSUE TITLE
@keypath([self new], someProperty) not work?

### ISSUE THREAD

**Issue by CodeLife2012** [jspahrsummers/libextobjc#117]
Sometimes may want to autofill a object in `@keypath(object, property)`, but we can't use  `[self new]`  or`[[self alloc] init]` because xCode treat  these object a`id` type.

Actually it's not a bug in this library, but anyone has a workaround for this?

**Comment by jspahrsummers** [comment]
`-init` and `+new` should be `instancetype`, not `id`, which means that dot syntax should compile.

**Comment by CodeLife2012** [comment]
@jspahrsummers 

 `[SomeClass new]` can work, but  in a class method` [self new] `or `[[self alloc] init] `is not work.

**Comment by jspahrsummers** [comment]
In that case, just use the class' name within the class method too:

```objc
@implementation SomeClass

+ (void)foo {
  … @keypath([SomeClass new], property) …
}
```

**Comment by k06a** [comment]
I am usually using it this way:
```
+ (NSDictionary *)JSONKeyPathsByPropertyKey {
    ResultObject *this = nil;
    return @{
        @keypath(this.url) : @"object.url",
        @keypath(this.summaryUrl) : @"object.extensions.summaryUrl",
        @keypath(this.title) : @"object.title",
        @keypath(this.favIconUrl) : @"faviconUrl",
        @keypath(this.backgroundImageUrl) : @"backgroundImageUrl",
        @keypath(this.fallbackImageUrl) : @"fallbackImageUrl",
        @keypath(this.backgroundImageSourceUrl) : @"backgroundImageSourceUrl",
    };
}
```

**Comment by CodeLife2012** [comment]
@k06a looks great
