### ISSUE TITLE
Push 0.5 to CocoaPods trunk

### ISSUE THREAD

**Issue by k06a** [jspahrsummers/libextobjc#118]
Please!

**Comment by jspahrsummers** [comment]
Sorry, I don't maintain any podspecs. I'd contact the most recent contributor(s) to the podspec and ask them to update it.

**Comment by ryanjm** [comment]
@jspahrsummers Are there any plans to add a podspec to the project?

Not sure what the process is, but as it is, the page on [cocoapods](https://cocoapods.org/pods/libextobjc) makes the project look really outdated.

**Comment by jspahrsummers** [comment]
No, no plans.
