### ISSUE TITLE
'OSSpinLock' is deprecated: first deprecated in iOS 10.0 - Use os_unfair_lock() from <os/lock.h> instead

### ISSUE THREAD

**Issue by southpeak** [jspahrsummers/libextobjc#126]
Hi, when i build the project, there are some warning about OSSpinLock, just like below

`
'OSSpinLock' is deprecated: first deprecated in iOS 10.0 - Use os_unfair_lock() from <os/lock.h> instead
`

**Comment by JuhaO81** [comment]
Any plans to fix this deprecation?

**Comment by diederich** [comment]
@JuhaO81 I'm not seeing it as the our utils library still deploys down to iOS 8 I think. Do you wanna send a PR?

**Comment by diederich** [comment]
see #130 for a PR
