### ISSUE TITLE
Installation throw CocoaPods not working

### ISSUE THREAD

**Issue by ramunasjurgilas** [jspahrsummers/libextobjc#136]
Missing installation throw CocoaPods.

It is not working:
pod 'libextobjc/EXTScope', :git => 'https://github.com/jspahrsummers/libextobjc.git', :tag => '0.6'

**Comment by flambert** [comment]
0.5 and 0.6 are not published: https://github.com/CocoaPods/Specs/tree/master/Specs/e/2/6/libextobjc

**Comment by diederich** [comment]
Closing in favour of #138
