### ISSUE TITLE
@weakify/@strongify in nested blocks

### ISSUE THREAD

**Issue by itsthejb** [jspahrsummers/libextobjc#45]
Hi,

I have been looking through the library documentation in order to find some guidance on how to use `@weakify` and `@strongify` in nested blocks, but cannot find any. For example, which is correct?

**1. `@weakify` once and subsequently `@strongify` in blocks**

```
- (void) test {
      @weakify(self)
      id block = ^{
        @strongify(self);
        [self doSomething];
        nestedBlock = ^{
          @strongify(self);
          [self doSomethingElse];
        }();
      };
      block();
}
```

**2. Alternate `@weakify`/`@strongify`**

```
- (void) test {
      @weakify(self)
      id block = ^{
        @strongify(self);
        [self doSomething];
        @weakify(self)         // @weakify again before the nested block?
        nestedBlock = ^{
          @strongify(self);
          [self doSomethingElse];
        }();
      };
      block();
}
```

Would be great to get some guidance on what is appropriate here.

Many thanks,

J

**Comment by trant** [comment]
What about for "parallel" blocks (blocks at the same level of scope)?  

[UIView animateWithDuration: kMapButtonsAnimationDuration
                          delay: 0
                        options: UIViewAnimationOptionCurveEaseOut
                     animations:^{
                         @strongify(self) 
                         [self superMan];
                    }
                     completion:^(BOOL finished){
                        [self completionMan];
                     }];

**Comment by Ricardo1980** [comment]
http://stackoverflow.com/questions/27019676/is-it-necessary-to-use-unowned-self-in-closures-of-uiview-animatewithduration

**Comment by nemissm** [comment]
@trant, you should write `@strongify` in completion too.

**Comment by k06a** [comment]
And don’t need `@strongify` In animation block.

**Comment by k06a** [comment]
Also aware access class members directly without specifying self this way: `self->xxx`

**Comment by k06a** [comment]
And don’t use `super` Key work in asynchronous blocks. Wrap calls in separate methods, which will be called by strongified `self` access.
