### ISSUE TITLE
Suggestions about EXTNil

### ISSUE THREAD

**Issue by xareelee** [jspahrsummers/libextobjc#52]
EXTNil is good. Here are the suggestions:
## 1. Using generic names for using EXTNil

Adding those two lines in the bottom of `EXTNil.h` header to use `EXTNil` more intuitive.

```
@compatibility_alias NilObj EXTNil;
#define nilObj [EXTNil null]
```

Using `nilObj` to present a null object, and `NilObj` to present the null object class. Those names are more generic.

And adding the following category implementation to help print the `nilObj` info.

```
@implementation EXTNil (Description)
- (NSString*)description {return @"<nilObj>";}
@end
```

And the output:

```
NSLog(@"%@", nil);
NSLog(@"%@", [NSNull null]);
NSLog(@"%@", nilObj);

==> (null)
==> <null>    
==> <nilObj>
```
## 2. Adding a universal null object test method.

There is no universal function/method to determine whether an object is `nil`, `NSNull`, or `EXTNil`. You can see the comparison below:

| When TestObject is | nil | NSNull | EXTNil |
| --- | --- | --- | --- |
| ! testObject | YES | NO | NO |
| TestObject == nil | YES | NO | NO |
| testObject == [NSNull null] | NO | YES | NO |
| [testObject isEqual:nil] | NO | NO | YES |
| [testObject isEqual:[NSNull null]] | NO | YES | YES |

My suggestion is adding a universal method `-isNotNilObj` to test an object:

```
// in EXTNil.h
@interface NSObject (NullObjectDesignPattern)
- (BOOL) isNotNilObj;
@end

// in EXTNil.m
@implementation NSObject (NullObjectDesignPattern)
- (BOOL) isNotNilObj {return YES;}
@end

@implementation NSNull (NullObjectDesignPattern)
- (BOOL) isNotNilObj {return NO;}
@end

@implementation EXTNil (NullObjectDesignPattern)
- (BOOL) isNotNilObj {return NO;}
- (NSString*)description {return @"<nilObj>";}
@end
```

Now, every object will return `YES` when receiving an `-isNotNilObj` message except the receiver is `nil`, `NSNull`, or `EXTNil`.

| TestObject | nil | NSNull | EXTNil |
| --- | --- | --- | --- |
| [testObject isNotNilObj] | NO | NO | NO |
| ![testObject isNotNilObj] | YES | YES | YES |
## 3. Make `[NSNull null]` return `nilObj` (EXTNil)

To make an old project can be compatible using `nilObj`, you may provide a convenient way to make `[NSNull null]` return `nilObj` (e.g. method swizzling). 
## 4. Convenient converting between `nil` and `nilObj`

Sometime you need to check whether an object is not `nil` before adding it into an `NSArray`, 'NSDictionary', or other object.

```
if (obj) {
    [array addObject:obj];
}
```

But with the following macros,

```
// return nilObj if the obj is nil; otherwise, return the obj itself.
#define nilObjify(obj) ([obj isNotNilObj]? obj:nilObj)
// return nil if the obj is nilObj; otherwise, return the obj itself.
#define nilify(obj) ([obj isNotNilObj]? obj:nil)
```

you can now write the code in one line:

```
[array addObject: nilObjify(obj)];
```

**Comment by jiangyewen** [comment]
id obj = [EXTNil null];
NSLog(@"channelName:%@",[obj testMethod]);

the code above crashes with info:
[NSProxy doesNotRecognizeSelector: testMethod]

Since EXTNil.null obj returns nil for all methods, why [obj testMethod] failed?

**Comment by jspahrsummers** [comment]
Do you define any `-testMethod` within your program? `EXTNil` doesn't make up methods—it simply finds a compatible signature from the methods which are registered.

**Comment by k06a** [comment]
@jiangyewen you can use this trick:
```
id obj = [EXTNil null];
NSLog(@"channelName:%@",[obj.self testMethod]);
```

This will works because `-[EXTNil self]` returns nil, all other classes just returns self.
