### ISSUE TITLE
CocoaPod packaging?

### ISSUE THREAD

**Issue by jacob414** [jspahrsummers/libextobjc#6]
Hello,

Very cool project.

Any plans on adding CocoaPod packaging? I made a naive [attempt](https://github.com/Plexical/libextobjc/tree/Xcode43-podable) attempt but immediately realised I was way over my head with that.

**Comment by edoardoc** [comment]
Hello, just a quick question:
is the pod safe to be used? as of today there is no mention of it in the readme.

PS: nice project
