### ISSUE TITLE
sizeof returning different values

### ISSUE THREAD

**Issue by 7ynk3r** [jspahrsummers/libextobjc#88]
For some reason `sizeof` is returning different values in my project compared to `extobcj`. I'm using `cocoapods` to link them together.

In particular, `sizeof(ext_propertyAttributes)` is returning 24 in my project and 28 in the library.

This causes a crash at runtime because things are not where they are supposed to be. 

Thanks,
JM

**Comment by 7ynk3r** [comment]
I tried compiling my project in 32-bits and 64-bits but the problem remains the same.

**Comment by jspahrsummers** [comment]
libextobjc definitely does not support 32-bit. It's also generally meant to be built as a _part of_ your project, not a separate library.

If you include the desired source files directly in your project, does that resolve the error?

**Comment by 7ynk3r** [comment]
Yes, if I include the files as part of my project the error gets solved. 

Thanks!
