### ISSUE TITLE
EXTConcreteProtocol on 8.3

### ISSUE THREAD

**Issue by floskel** [jspahrsummers/libextobjc#91]
Im seing crashes when using a concrete protocol on iOS 8.3. 
Its a simple `unrecognized selector sent to instance` on the classes that adapts to the concrete protocol. 
Anyone else seeing the same problems? It works as intended on 8.2

**Comment by jspahrsummers** [comment]
I haven't seen this myself, and I'm afraid I don't have time to dig into it (particularly as I don't have any active projects that use concrete protocols anymore).

Just in case I or somebody else were to take a look, though, an example project demonstrating the issue would be super helpful. :pray:

**Comment by floskel** [comment]
This was a stupid mistake on my part. The protocol was not included in the correct target. Closing this as it works as expected.

**Comment by jspahrsummers** [comment]
Thanks for the update!
