### ISSUE TITLE
Could not add instance method -dealloc to UIViewController ?

### ISSUE THREAD

**Issue by GreatFireWall** [jspahrsummers/libextobjc#92]
ERROR: Could not add instance method -dealloc to UIViewController (a method by the same name already exists)
ERROR: Failed to fully load safe category UIViewController (Logger)

@safecategory(UIViewController, Logger)

- (void)dealloc {
    NSLog(@"%@ dealloc", self.class);
}

@end

**Comment by jspahrsummers** [comment]
The error message is pretty straightforward, and clear about what the issue is. What's your question?

**Comment by GreatFireWall** [comment]
I want to hook the -dealloc method and doesn't override it , how can i do by  @safecategory?

**Comment by jspahrsummers** [comment]
Safe categories can't inject methods that already exist on the destination class. In this case, `UIViewController` already has a `-dealloc` method, and it would be dangerous to overwrite it.

Instead, you could add a breakpoint on `-[UIViewController dealloc]`, and log to the console there. Hope that helps!

**Comment by GreatFireWall** [comment]
sorry, i don't understand how to use @safecategory ? Or to say what can i do by @safecategory?
 -_- ||

**Comment by jspahrsummers** [comment]
EXTSafeCategory is intended to be used to add methods to a class _while ensuring_ that they don't conflict with any existing methods. It's not suitable for method _overriding_.

**Comment by GreatFireWall** [comment]
ok, thanks.
