### ISSUE TITLE
How to use synthesizeAssociation function?

### ISSUE THREAD

**Issue by jkyin** [jspahrsummers/libextobjc#97]
Here is my class;

.h
```objc
#import <UIKit/UIKit.h>

@interface UIView (TFUmengAnalytics)
@property (nonatomic, copy) NSDictionary *tf_umengDictionary;
@end
```

.m
```objc
@implementation UIView (TFUmengAnalytics)
synthesizeAssociation(UIView, tf_umengDictionary);
@end
```

but, I got a error:
![qq20151031-0 2x](https://cloud.githubusercontent.com/assets/1644903/10862773/bee6645c-7ff1-11e5-8194-a83c406328a8.png)

Anyone can help me? Please....

**Comment by jspahrsummers** [comment]
You need to prefix `synthesizeAssociation` with an `@` symbol, just like the built-in keywords.

**Comment by jkyin** [comment]
![qq20151103-0 2x](https://cloud.githubusercontent.com/assets/1644903/10899581/1b19d0d0-8211-11e5-9044-bcbc9a3af047.png)

Thank you @jspahrsummers , it works. But why there isn't syntax highlighting for `synthesizeAssociation`. And also I cannot use command+click to jump to define.

**Comment by jspahrsummers** [comment]
![](http://cdn.meme.am/instances/55684505.jpg)
